version: 2.1
jobs:
 build:
   machine: true
   steps:
     ## tools
     - run: sudo apt-get update
     #- run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
     ##- run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 74E6910DFCB68C9CD
     #- run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
     #- run: sudo apt-get update
     #- run: sudo apt-get update && apt-get install -y libffi-dev libssl-dev python3-dev python3 python3-pip
     #- run: pip3 install docker-compose

     ## (legacy) circleci recently seems to have issues with signatures...
     - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     - run: sudo chmod a+x /usr/local/bin/docker-compose

     ## setup only
     - checkout
     - run: cd ./docker && echo "UID=$(id -u)" > .env && echo "GID=$(id -g)" >> .env && docker-compose up --exit-code-from sandbox
